sudo: required

language: ruby

services:
  - docker

before_install:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker pull carlad/sinatra
- docker images
- docker tag carlad/sinatra ritpraja/sinatra
- docker push ritpraja/sinatra


script:
- bundle exec rake test
